### ISSUE TITLE
Is the cpu metric available?

### ISSUE THREAD

**Issue by BongChan** [cloudfoundry-incubator/app-autoscaler#133]
Looking at the code, it appears that the relevant code for the cpu is still under development.
If i simply modify the policy registration (Constants.metrictype: public static String[] metrictype = {METRIC_TYPE_MEMORY, "CPU"};) part, auto scaling seems to work with the cpu metric.
Could it be used this way?
For some reason, is the cpu metric unusable?

**Comment by fraenkel** [comment]
We have no plans to expose the CPU metric. We are building this to make other metrics possible and our first goal is memory. CPU is problematic because it doesn't provide enough detail to make an accurate assessment. In CF, an application can be given any amount of available CPU. If we were to see an application use 800% CPU, does it mean we should scale out? It is using what is available which isn't a bad thing. Until we have enough data to decide that CPU is being exhausted, we are avoiding it.

**Comment by jtwaleson** [comment]
@fraenkel can this be reconsidered? We are running with the cpu_quota_per_share_in_us setting and thereby limiting the CPU shares that containers can use. If we are close to the limit we would like to scale up applications.
